[project]
name = "nonebot-plugin-ottohzys"
version = "0.1.1.post1"
description = "otto!"
authors = [{ name = "student_2333", email = "lgc2333@126.com" }]
dependencies = [
    "nonebot2>=2.0.0",
    "nonebot-adapter-onebot>=2.2.0",
    "pydantic>=1.10.4,<2",
    "soundfile>=0.12.1",
    "numpy>=1.24.4",
    "pypinyin>=0.49.0",
    "psola>=0.0.1",
    "anyio>=4.0.0",
    "httpx>=0.25.0",
]
requires-python = ">=3.8,<4.0"
readme = "README.md"
license = { text = "MIT" }

[project.urls]
homepage = "https://github.com/lgc-NB2Dev/nonebot-plugin-ottohzys"

[tool.pdm.build]
includes = []

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
