[project]
name = "nonebot-plugin-ottohzys"
dynamic = ["version"]
description = "otto!"
authors = [{ name = "LgCookie", email = "lgc2333@126.com" }]
dependencies = [
    "nonebot2>=2.3.1",
    "nonebot-plugin-alconna>=0.48.0",
    "soundfile>=0.12.1",
    "numpy>=1.26.4",
    "pypinyin>=0.51.0",
    "psola>=0.0.1",
    "anyio>=4.4.0",
    "httpx>=0.27.0",
    "async-lru>=2.0.4",
]
requires-python = ">=3.9,<4.0"
readme = "README.md"
license = { text = "MIT" }

[project.urls]
homepage = "https://github.com/lgc-NB2Dev/nonebot-plugin-ottohzys"

[tool.pdm.build]
includes = []

[tool.pdm.version]
source = "file"
path = "nonebot_plugin_ottohzys/__init__.py"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
