[project]
name = "nonebot-plugin-ottohzys"
dynamic = ["version"]
description = "otto!"
authors = [{ name = "student_2333", email = "lgc2333@126.com" }]
dependencies = [
    "nonebot2>=2.2.0",
    "nonebot-plugin-alconna>=0.40.0rc1",
    "soundfile>=0.12.1",
    "numpy>=1.24.4",
    "pypinyin>=0.49.0",
    "psola>=0.0.1",
    "anyio>=3.6.2",
    "httpx>=0.25.0",
    "async-lru>=2.0.4",
]
requires-python = ">=3.9,<4.0"
readme = "README.md"
license = { text = "MIT" }

[project.urls]
homepage = "https://github.com/lgc-NB2Dev/nonebot-plugin-ottohzys"

[tool.pdm.build]
includes = []

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
